### ISSUE TITLE
Build error after "kmodules" commits

### ISSUE THREAD

**Issue by acras01** [AospExtended/platform_vendor_aosp#28]
After sincing sources these commits ( http://gerrit.aospextended.com/q/topic:%22kmodules%22+(status:open%20OR%20status:merged) ) cause error https://del.dog/halayiquxi.coffeescript

**Comment by 18796299507** [comment]
I have the same problem ，my device is lavender

**Comment by acras01** [comment]
Latest commit didn't fix it
![photo_2019-07-23_09-51-44](https://user-images.githubusercontent.com/1431381/61689274-90727880-ad2f-11e9-9d96-0028139442c6.jpg)

**Comment by 18796299507** [comment]
Return the kernel.mk file to ten days ago and it can be fixed

**Comment by acras01** [comment]
> Return the kernel.mk file to ten days ago and it can be fixed

This can't be a fix

**Comment by 18796299507** [comment]
you can override kernel.mk with https://del.dog/cafoyevaho , i can ues it to compile normally
